# Generated by Django 4.0.4 on 2022-05-28 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jumla', '0007_bill_items_alter_bill_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='quantity',
        ),
    ]
