# Generated by Django 4.0.4 on 2022-05-29 06:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jumla', '0008_remove_bill_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='Date',
            field=models.DateTimeField(verbose_name=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cart',
            name='Date',
            field=models.DateTimeField(verbose_name=django.utils.timezone.now),
        ),
    ]
