# Generated by Django 4.0.4 on 2022-05-29 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jumla', '0009_alter_bill_date_alter_cart_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='Governorate',
        ),
        migrations.CreateModel(
            name='Cart_Governorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Governorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_Governorate', to='jumla.governorate')),
                ('cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_id', to='jumla.cart')),
            ],
        ),
    ]
