# Generated by Django 4.0.4 on 2022-05-29 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jumla', '0011_alter_bill_date_alter_cart_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill_items',
            name='qty',
            field=models.IntegerField(default=1),
        ),
    ]
